"""
bhch12exrc13.py: Print out all combinations of the string 'Python' plus a three letter English word. Capitalize the first letter of the three letter word. Example combinations are 'PythonCat', 'PythonDog', and 'PythonTag'. These are valid combinations because cat, dog, and tag are English words. On the other hand, 'PythonQqz' would not be a valid combination because qqz is not an English word. Use a wordlist to determine which three letter combinations are words.
"""
print('*'*80)

all_words = [line.strip() for line in open('wordlist.txt')]

for i in all_words:
	if len(i) == 3:
		print('Python{:}, '.format(i[0].upper() + i[1:].lower()), end='')
print()

print('*'*80)
"""PROGRAM OUTPUT
********************************************************************************
PythonAaa, PythonAbc, PythonAbs, PythonAbu, PythonAcc, PythonAce, PythonAcm, PythonAct, PythonAda, PythonAdd, PythonAds, PythonAge, PythonAgo, PythonAid, PythonAim, PythonAir, PythonAka, PythonAla, PythonAli, PythonAll, PythonAlt, PythonAmd, PythonAmp, PythonAmy, PythonAna, PythonAnd, PythonAnn, PythonAnt, PythonAny, PythonAol, PythonApi, PythonApp, PythonApr, PythonApt, PythonArc, PythonAre, PythonArg, PythonArm, PythonArt, PythonAsh, PythonAsk, PythonAsn, PythonAsp, PythonAss, PythonAta, PythonAte, PythonAti, PythonAtm, PythonAud, PythonAug, PythonAus, PythonAve, PythonAvg, PythonAvi, PythonAye, PythonBad, PythonBag, PythonBan, PythonBar, PythonBat, PythonBay, PythonBbc, PythonBbs, PythonBbw, PythonBed, PythonBee, PythonBen, PythonBet, PythonBid, PythonBig, PythonBin, PythonBio, PythonBit, PythonBiz, PythonBmw, PythonBob, PythonBoc, PythonBon, PythonBow, PythonBox, PythonBoy, PythonBra, PythonBuf, PythonBug, PythonBus, PythonBut, PythonBuy, PythonBye, PythonCab, PythonCad, PythonCal, PythonCam, PythonCan, PythonCap, PythonCar, PythonCas, PythonCat, PythonCbs, PythonCcd, PythonCds, PythonCdt, PythonCeo, PythonCet, PythonCfr, PythonCgi, PythonChi, PythonCho, PythonCia, PythonCio, PythonCir, PythonCms, PythonCnn, PythonCod, PythonCol, PythonCom, PythonCon, PythonCop, PythonCos, PythonCow, PythonCox, PythonCpu, PythonCrm, PythonCry, PythonCss, PythonCst, PythonCum, PythonCup, PythonCut, PythonCvs, PythonDad, PythonDam, PythonDan, PythonDas, PythonDat, PythonDay, PythonDdr, PythonDec, PythonDee, PythonDef, PythonDel, PythonDem, PythonDen, PythonDer, PythonDes, PythonDev, PythonDid, PythonDie, PythonDig, PythonDim, PythonDip, PythonDir, PythonDis, PythonDiv, PythonDiy, PythonDna, PythonDns, PythonDoc, PythonDod, PythonDoe, PythonDog, PythonDom, PythonDon, PythonDos, PythonDot, PythonDow, PythonDpi, PythonDry, PythonDsc, PythonDsl, PythonDts, PythonDue, PythonDui, PythonDuo, PythonDvd, PythonEar, PythonEat, PythonEau, PythonEco, PythonEds, PythonEdt, PythonEgg, PythonEnb, PythonEnd, PythonEng, PythonEnt, PythonEos, PythonEpa, PythonEra, PythonErp, PythonEst, PythonEtc, PythonEur, PythonEva, PythonEve, PythonExp, PythonExt, PythonEye, PythonFan, PythonFaq, PythonFar, PythonFat, PythonFax, PythonFbi, PythonFcc, PythonFda, PythonFeb, PythonFed, PythonFee, PythonFew, PythonFig, PythonFin, PythonFit, PythonFix, PythonFla, PythonFlu,
PythonFly, PythonFog, PythonFoo, PythonFor, PythonFox, PythonFri, PythonFtp, PythonFun, PythonFur, PythonFwd, PythonGap, PythonGas, PythonGay, PythonGba, PythonGbp, PythonGcc, PythonGdp, PythonGel, PythonGem, PythonGen, PythonGeo, PythonGet, PythonGhz, PythonGif, PythonGig, PythonGis, PythonGmc, PythonGmt, PythonGnu, PythonGod, PythonGot, PythonGov, PythonGpl, PythonGps, PythonGsm, PythonGst, PythonGtk, PythonGui, PythonGun, PythonGuy, PythonGym, PythonHad, PythonHam, PythonHas, PythonHat, PythonHay, PythonHer, PythonHey, PythonHim, PythonHip, PythonHis, PythonHit, PythonHiv, PythonHon, PythonHop, PythonHot, PythonHow, PythonHrs, PythonHub, PythonHwy, PythonIan, PythonIbm, PythonIce, PythonIcq, PythonIct, PythonIde, PythonIds, PythonIii, PythonIll, PythonIma, PythonImg, PythonInc, PythonInd, PythonInf, PythonIng, PythonInk, PythonInn, PythonIns, PythonInt, PythonIon, PythonIps, PythonIra, PythonIrc, PythonIrs, PythonIsa, PythonIso, PythonIsp, PythonIst, PythonIts, PythonJam, PythonJan, PythonJar, PythonJay, PythonJet, PythonJim, PythonJob, PythonJoe, PythonJon, PythonJoy, PythonJpg, PythonJul, PythonJun, PythonJvc, PythonKai, PythonKay, PythonKde, PythonKen, PythonKey, PythonKid, PythonKim, PythonKit, PythonLab, PythonLan, PythonLap, PythonLas, PythonLat, PythonLaw, PythonLay, PythonLbs, PythonLcd, PythonLed, PythonLee, PythonLeg, PythonLen, PythonLeo, PythonLes, PythonLet, PythonLeu, PythonLib, PythonLid, PythonLie, PythonLil, PythonLip, PythonLit, PythonLiz, PythonLlc, PythonLlp, PythonLoc, PythonLog, PythonLol, PythonLos, PythonLot, PythonLou, PythonLow, PythonLtd, PythonMac, PythonMad, PythonMae, PythonMag, PythonMai, PythonMan, PythonMap, PythonMar, PythonMas, PythonMat, PythonMax, PythonMay, PythonMba, PythonMed, PythonMel, PythonMem, PythonMen, PythonMet, PythonMfg, PythonMhz, PythonMia, PythonMic, PythonMid, PythonMil, PythonMin, PythonMit, PythonMix, PythonMlb, PythonMls, PythonMod, PythonMom, PythonMon, PythonMpg, PythonMph, PythonMrs, PythonMsg, PythonMsn, PythonMtv, PythonMud, PythonMug, PythonNam, PythonNat, PythonNav, PythonNba, PythonNbc, PythonNec, PythonNeo, PythonNet, PythonNew, PythonNfl, PythonNhl, PythonNhs, PythonNil, PythonNon, PythonNor, PythonNos, PythonNot, PythonNov, PythonNow, PythonNsw, PythonNut, PythonNyc, PythonOak, PythonObj, PythonOct, PythonOdd, PythonOem, PythonOff, PythonOil, PythonOld,
PythonOne, PythonOns, PythonOoo, PythonOpt, PythonOrg, PythonOur, PythonOut, PythonOwn, PythonPac, PythonPad, PythonPal, PythonPam, PythonPan, PythonPar, PythonPas, PythonPat, PythonPay, PythonPci, PythonPcs, PythonPct, PythonPda, PythonPdf, PythonPdt, PythonPee, PythonPen, PythonPer, PythonPet, PythonPgp, PythonPhd, PythonPhi, PythonPhp, PythonPic, PythonPie, PythonPig, PythonPin, PythonPit, PythonPix, PythonPlc, PythonPmc, PythonPod, PythonPop, PythonPor, PythonPos, PythonPot, PythonPpc, PythonPpm, PythonPre, PythonPro, PythonPsi, PythonPsp, PythonPst, PythonPts, PythonPty, PythonPub, PythonPut, PythonPvc, PythonQld, PythonQty, PythonQue, PythonQui, PythonRam, PythonRan, PythonRap, PythonRat, PythonRaw, PythonRay, PythonRca, PythonRec, PythonRed, PythonRef, PythonReg, PythonRel, PythonRep, PythonRes, PythonRev, PythonRfc, PythonRid, PythonRim, PythonRio, PythonRip, PythonRna, PythonRob, PythonRod, PythonRom, PythonRon, PythonRow, PythonRoy, PythonRpg, PythonRpm, PythonRrp, PythonRss, PythonRug, PythonRun, PythonSad, PythonSam, PythonSan, PythonSao, PythonSap, PythonSas, PythonSat, PythonSaw, PythonSay, PythonSci, PythonSea, PythonSec, PythonSee, PythonSen, PythonSeo, PythonSep, PythonSeq, PythonSer, PythonSet, PythonSex, PythonShe, PythonSic, PythonSie, PythonSig, PythonSim, PythonSin, PythonSip, PythonSir, PythonSit, PythonSix, PythonSki, PythonSku, PythonSky, PythonSms, PythonSoa, PythonSoc, PythonSol, PythonSon, PythonSox, PythonSpa, PythonSpy, PythonSql, PythonSrc, PythonSri, PythonSsl, PythonStd, PythonSte, PythonStr, PythonSub, PythonSue, PythonSum, PythonSun, PythonSur, PythonSys, PythonTab, PythonTag, PythonTan, PythonTap, PythonTar, PythonTax, PythonTba, PythonTcp, PythonTea, PythonTed, PythonTee, PythonTel, PythonTen, PythonTex, PythonTft, PythonTgp, PythonThe, PythonThu, PythonThy, PythonTie, PythonTil, PythonTim, PythonTin, PythonTip, PythonTit, PythonTmp, PythonToe, PythonTom, PythonTon, PythonToo, PythonTop, PythonToy, PythonTri, PythonTry, PythonTub, PythonTue, PythonTvs, PythonTwo, PythonUna, PythonUnd, PythonUne, PythonUni, PythonUpc, PythonUps, PythonUri, PythonUrl, PythonUrw, PythonUsa, PythonUsb, PythonUsc, PythonUsd, PythonUse, PythonUsr, PythonUtc, PythonVal, PythonVan, PythonVar, PythonVat, PythonVcr, PythonVer, PythonVhs, PythonVia, PythonVic, PythonVid, PythonVii, PythonVip, PythonVol, PythonVon,
PythonVpn, PythonWal, PythonWan, PythonWar, PythonWas, PythonWav, PythonWax, PythonWay, PythonWeb, PythonWed, PythonWet, PythonWho, PythonWhy, PythonWin, PythonWit, PythonWma, PythonWon, PythonWow, PythonWto, PythonWww, PythonXml, PythonXxx, PythonYea, PythonYen, PythonYes, PythonYet, PythonYou, PythonYrs, PythonZen, PythonZip, PythonZoo, PythonZum, PythonZus,
********************************************************************************
"""